#!/usr/bin/env python
# coding: utf-8

# In[1]:



arabic_location_mapping = {'jeddah':'KSA','الخبر':'KSA','Libya ':'Libya','Kingdom of Saudi Arabia Riyadh':'KSA','Amman':'Jordan',
                    'Riyadh':'KSA','Riyadh  Kingdom of Saudi Arabia':'KSA','الخاص مهمل تماماً':'unknown','London  England':'UK','السعوديه':'KSA',
                    'دولة الإمارات   أبوظبي':'UAE','Dubai  United Arab Emirates':'UAE','لبنان':'Lebanon','Lebanon  Bekaa':'Lebanon','Brooklyn  NY':'USA',
                    'nan':'unknown','أخبار العالم':'unknown','مش مهم':'unknown','الرياض  المملكة العربية السعودية':'KSA','Beirut lebanon':'Lebanon','ارض امنا حواء':'unknown',
                    'Lebanon  TN':'Lebanon','المملكة العربية السعودية':'KSA',' leo ':'unknown','Hawally  Kuwait':'Kuwait','saudi  Riyadh':'KSA',' ':'unknown',
                    'مصر  المنصوره   دقهليه':'Egypt','kuwait':'Kuwait','بيروت   لبنان':'Lebanon','القنفذة  المملكة العربية السعودية':'KSA','الفيحاء  دولة الكويت':'Kuwait','Beirut':'Lebanon',
                    'الاردن':'Jordan','المملكه العربيه السعوديه':'KSA','الرياض':'KSA','saudi':'KSA','الرياض  المملكة العربية السعود':'KSA','Stretford End  2nd tier':'unknown',
                    'El Monofia  Egypt':'Egypt','Seddiqine  Lebanon ':'Lebanon','الكويت':'Kuwait','جدة  المملكة العربية السعودية':'KSA','Hashemite Kingdom of Jordan':'Jordan',
                    'kuwait  ':'Kuwait','دولة الكويت':'Kuwait','Lebanon Nabateih':'Lebanon','Kurdistan':'Iraq','فلسطين  خانيونس':'Palestine','رفحاء  المملكة العربية السعودي ':'KSA',
                    'Raouche Karakas  Jurdi Bldg':'Lebanon','الجبيل البلد':'KSA','Mishrif  Kuwait':'Kuwait','المملكة العربيةالسعودية':'KSA','جيزان المملكه العربيه السعودية':'KSA',
                    'مملكة البحرين الرفاع العز':'Bahrain','العاصمه  دولة الكويت':'Kuwait','Tel Aviv Jaffa':'Palestine','القصيم':'KSA',' بيروت  لبنان':'Lebanon','منطقة الرياض':'KSA',
                    'مكة المكرمة  السعوديه':'KSA','صفوى  المملكة العربية السعودية':'KSA','Vancouver  British Columbia':'UK','H rn sand  Sverige':'unknown','القاهرة':'Egypt',
                    'الشفاء  المملكة العربية السعودية':'KSA','Grand Casablanca':'Morocco','الرياض  المملكة العربية':'KSA','جازان  المملكة العربية السعودي ':'KSA','Brighton  England':'UK',
                    'فلسطين':'Palestine','yemj111 gmail com':'unknown','القاهرة  مصر':'Egypt','l Afrique':'unknown','غزة':'Palestine','  دولة الكويت':'Kuwait',
                    'Casablanca Bruxelles':'Morocco','Saudi Arabia':'KSA','مكة المكرمة  المملكة العربية السعودية':'KSA','Amman  ':'Jordan','درب السعادة':'KSA','البحرين':'Bahrain',
                    'Rabat':'Morocco','Paris  France':'France','Stockholm':'Sweden','الخبر  المملكة العربية السعودية':'KSA','Egypt  PA':'Egypt','الوكرة  دولة قطر':'Qatar',
                    'لا إله الا انت ربي، استغفرك':'unknown','Royaume du Maroc':'Morocco','Somewhere  Saudi Arabia':'KSA','الرياض  الخرج السيح ':'KSA','liban  tyre':'Lebanon',
                    'Lebanon nabatieh':'Lebanon','الولايات المتحدة الأمريكية':'USA','المدينة المنورة':'KSA','Rabat  Morocco':'Morocco','جده المملكه العربية السعودية':'KSA',
                    'Saudi Arabia  Jeddah':'KSA','دولة الكويت العظمى ':'Kuwait','المملكةالعربيةالسعودية  الجنوب ':'KSA','جازان المملكة العربية السعودية':'KSA','غياهب الدنيا':'KSA',
                    'Tyre  Lebanon':'Lebanon','الدوحة، قطر':'Qatar','Kuwait  ':'Kuwait','جازان':'KSA','بلغازي   السعودية':'KSA','الدمام':'KSA',
                    'النجم الثاقب   Kuwait':'Kuwait','Palestine  TX':'Palestine','Doha  Qatar':'Qatar','Info marsalqatar qa':'unknown','KSA   بلغازي':'KSA',
                    'Jeddah':'KSA','QATAR':'Qatar','القصيم  المملكة العربية السعودية':'KSA','aljubail':'KSA','Abu Dhabi':'UAE','مصر':'Egypt','Ile de France  France':'France',
                    'Gaza Strip   Palesitne':'Palestine','Cairo  Egypt':'Egypt','أزقة التغريد وضواحيها':'KSA','Q8':'unknown','Amsterdam  Nederland':'Netherland',
                    'Curva Nord   Lazio Ultras':'France','Qatar   Doha':'Qatar','ksa':'KSA','الخرج   الدلم':'KSA','United Arab Emirates':'UAE',
                    'أربيل، إقليم كوردستان':'Iraq','Muscat  Oman':'Oman','بلد المقاوم و البوصلة ':'unknown','كفر منصور الدوله':'unknown','  في قلب من أحبهم أكون  ':'unknown',
                    'شيخ روحاني جلب الحبيب فك السحر':'unknown','El Gharbia  Egypt':'Egypt','London  GB':'UK','عفيف  المملكة العربية السعودية':'KSA','El Daqahlia  Egypt':'Egypt',
                    'القاهرة   مصر':'Egypt','UAE   DUBAI':'UAE','أرض الله الواسعة':'unknown','مكة المكرمة':'KSA','somewhere':'unknown','منطقة عسير':'KSA','المغرب':'Morocco',
                    'جدة  مكة المكرمة':'KSA','أسوان  مصر':'Egypt','مملكة البحرين':'Bahrain',' على سواحل بلادي العذيّه':'unknown','Dubai London Beirut':'Lebanon',
                    'السعودية المنطقة الشرقية الخبر':'KSA','الإمارات العربية المتحدة':'UAE','الكويت   حرسها الله':'Kuwait','المصنعه  ':'Oman','Al Andalous  Kuwait':'Kuwait',
                    'الباحة':'KSA','بنى سويف  مصر':'Egypt','Aus   Oman':'Oman','رئيسة قسم لغة عربية':'unknown','USA   Florida':'USA','ROBLOX':'unknown',
                    'علبة السُكر':'unknown','BATH UK':'UK','Bsous lebanon':'Lebanon','Saudi arabia   Riyadh':'KSA','الخور  دولة قطر':'Qatar','القريات':'KSA',' الطائف':'KSA',
                    'Eastern':'unknown','United States':'USA','جبل عامل':'KSA','على خشوم الحثالات وخدم المحتل':'unknown','El Menia  Egypt':'Egypt','Maroc':'Morocco',
                    'kw':'Kuwait','تبوك المملكة العربية السعودية':'KSA','Tanger  Maroc':'Morocco','Riyadh  KSA':'KSA','السعودية':'KSA','Agadir':'KSA',
                    '  بيّن الأغاني والشِعر  ':'unknown','cairo  Egypt':'Egypt','Saudi Arabia   al majmaah':'KSA', 'عمان المملكة الأردنية الهاشمية':'Jordan','الأسكندرية  مصر':'Egypt',
                    'Officialy   Digital   Globaly ':'unknown','تبوك  المملكة العربية السعودية':'KSA','العراق':'Iraq','American River  South Australi':'USA',
                    'العقيلة  دولة الكويت':'Kuwait','مبارك الكبير بوفطيرة':'unknown','planet earth':'unknown','شرورة':'KSA','الخُبر السعودية':'KSA','Libya Benghazi':'Libya',
                    'lebanon Bekaa Maydoun ':'Lebanon','حائل قطعة من قلبي':'KSA',' مكة المكرمة ':'KSA','الامارات العربية المتحدة  ':'UAE','El Sharkia  Egypt':'Egypt',
                    'West london':'UK',' stanbul  T rkiye':'Turkey','Liban':'Lebanon',' ناشط لاشط':'unknown',' أرض ربي تنومة شعف آل سودة':'unknown','Cloud':'unknown',
                    'The Great Saudi Arabia ':'KSA','الطائف  المملكة العربية السعود':'KSA','شرورة  المملكة العربية السعودي':'KSA','Kingdom of Saudi Arabia':'KSA',
                    'مسقط  سلطنة عمان':'Oman','  الولايات المتحده الصدامية':'unknown','مصر   كفرالشيخ مطوبس برج مغيزل':'Egypt','Mother of the world   ':'unknown',
                    'العالم المحتضر':'unknown','تبوك  السعودية ٠٥٠٧٥٦٩٠٥٠':'KSA','الدوحة  دولة قطر':'Qatar','KUWAIT':'Kuwait','ينبع الصناعية  المملكة العربية':'KSA',
                    'والقزاع يختم مانطق من احاسيس':'unknown','I walk business Management':'unknown','الدمام  المملكة العربية السعود':'KSA','lebanon':'Lebanon','حيث أُحترم':'unknown',
                    'Old Trafford':'unknown','العراق النجف الاشرف':'Iraq','El Qaliobia Egypt ':'Egypt','Dubai    ':'UAE','Amman   Jordan':'Jordan',
                    'Makkah Al Mukarrama':'KSA','جلاجل اقليم سدير':'KSA','بريدة':'KSA','المجمعة  المملكة العربية السعو':'KSA','Aleppo':'Syria','    pyeong yang':'unknown',
                    'The Capital  Kuwait':'Kuwait','الخليج العربي   Arabian Gulf':'KSA','آلجہزآئر':'Algeria','القنفذة   الرياض KSA ،  ':'KSA','Karaman':'KSA','٩  ':'unknown',
                    ' T  24 472144 54 373405':'unknown','Epoch':'unknown','Greeley  Colorado':'USA','Cairo':'Egypt','Tanger M dina  Royaume du Maro':'Morocco',
                    'بغداد   حي الخضراء':'Iraq','alexandria egypt':'Egypt','Al Adailiya  Kuwait':'Kuwait','الشرقي':'UAE','اليمن العظمى':'Yemen',' الكويت في المناهج العراقية':'Kuwait',
                    'زُحل':'unknown','حائل  المملكة العربية السعودية':'KSA','اللهم الفردوس لجدتي امنه':'unknown','Beirut   Lebanon':'Lebanon','Any pronoun   XNFJ':'unknown',
                    'Jazan  Kingdom of Saudi Arabia':'KSA','Tripoli   Paris':'Lebanon','سوهاج  مصر':'Egypt','Washington  DC':'USA','الدوحه':'Qatar',
                    'السعودية':'KSA','السعودية العظمى  ':'KSA','Amman Jordan':'Jordan','We Go Again':'unknown','الرستاق  سلطنة عمان':'Oman','شناص':'UAE',
                    'Arabian Gulf   Kuwait  ':'Kuwait','سلطنة عمان':'Oman','Oman Muscat':'Oman',' البنات أحلا الكائنات ':'unknown','Riyadh   Ksa ':'KSA',
                    ' mundial11news':'unknown','العديليه  دولة الكويت':'Kuwait','رحم الله أبي':'unknown','  قطر العز والخير   تميم المجد':'Qatar','Highbury Stadium  ':'unknown',
                    'Ljubljana':'unknown','السعودية   بريدة   المريدسية':'KSA','الجهراء  دولة الكويت':'Kuwait','الخاص للإعلانات':'unknown','اسطنبول   تركيا':'Turkey','العالم الإسلامي':'unknown',
                    'المملكة المغربية':'Morocco','الامارات  ابوظبي':'UAE','الخبر المملكة العربية السعوديه':'KSA','El awamyh ':'unknown','Beirut  Lebanon':'Lebanon','كفر الشيخ  مصر':'Egypt',
                    'فـلـسـطـيـن الجليل الأعلى':'Palestine','Jounieh':'Lebanon','Achrafieh Beirut':'Lebanon','تونس':'Tunisia','أنا من جنود الله حزب محمد':'unknown',
                    'Australia  Victoria  Melbourne':'Australia','Estuaire  Gabon':'unknown','انصاري وبحرام جذمي ومسكني':'unknown','الشرقية  مصر':'Egypt',
                    'Alexandria  Egypt':'Egypt','السويس  مصر':'Egypt','اينما يكون الحق والعدل اكون':'unknown','Jerusalem  Israel':'Palestine','محور المقاومة':'unknown',
                    'طاريا ؛ البقاع':'Lebanon','أورشليم القدس  اسرائيل':'Palestine','Swat':'unknown','El Qaliobia  El Qanater  Egypt':'Egypt','موريتانيا':'Mauritania',
                    'بلاد الارز':'Lebanon','البعد عن الناس راحه':'unknown','Abu Dhabi  United Arab Emirates':'UAE','JC Kuwait':'Kuwait','samanoud':'unknown',
                    'Failaka   Kuwait':'Kuwait','الغربية  مصر':'Egypt','Tripoli Libye':'Libya','مختار التتش':'unknown','Qena':'unknown','10452':'unknown',
                    'Alskhamah':'unknown','بشنق بيت جارنا':'unknown','Gulf':'UAE','Casablanca  Grand Casablanca':'Morocco','Saudi Arabia  Riyadh':'KSA',
                    'Cairo Egypt':'Egypt','المدينة المنورة  السعودية':'KSA','KUWAIT IN My  ':'Kuwait','في قلبه':'unknown','t me Palinfo':'unknown','Temporary Syria':'Syria',
                    'Nuuk':'unknown','Cairo  GA':'Egypt','أسيوط  مصر':'Egypt','    DXB':'unknown','Israel':'Palestine','سورياالاسد':'Syria','cairo egypt':'Egypt',
                    'مدينتي ':'unknown','JEDDAH':'KSA','قلوة، المملكة العربية السعودية':'KSA','مكة المكرمة  المملكة العربية ا':'KSA','Mesopotamia':'unknown','Failaka Island  Kuwait':'Kuwait',
                    'Dijon  France':'France','Esp rito Santo  Brasil':'Brazil','Syrian':'Syria','Oregon  USA':'USA','Egypt  bns':'Egypt','القنفذة':'KSA',
                    'القصيم المملكة العربية السعود':'KSA','Berkayel  Akkar':'Lebanon','المملكة الأردنية الهاشمية':'Jordan','عرعر  المملكة العربية السعودية':'KSA','السعوديه  الرياض':'KSA',
                    'مصر':'Egypt','Egypt حسابي الاساسي':'Egypt','Lebanon  Beirut':'Lebanon','beirut':'Lebanon','in my mind':'unknown','حائل':'KSA',
                    'saudi arabia jeddah':'KSA','المنوفية  مصر':'Egypt','في كل الكون':'unknown','Al Hajj Hafez':'Lebanon','world':'unknown',' HYUN3UK  vampirelole ':'unknown',
                    'Italia':'Italy','Egypt   مصر':'Egypt','العالم':'unknown','West Asia':'unknown','El Mahalla El kubra':'unknown','winterfell':'unknown',
                    'الدقهلية  مصر':'Egypt','الاحساء  المملكة العربية السعودية':'KSA','Sharq  Kuwait  ':'Kuwait','Norway Oslo':'Norway','الشعراء':'unknown','تحت رحمة الرحمن':'unknown',
                    'المدينة المنورة  المملكة العربية السعودية':'KSA','Domiat  Egypt':'Egypt','اذكروني بدعوه':'unknown','Adma Lebanon':'Lebanon','tanta  قلبي في التتش زي سوفا ':'unknown',
                    'ابوظبي جنة الأمن والأمان':'UAE','عجمان، الإمارات ':'UAE','المملكه العربية السعودية':'KSA','  فيلچا ياحبيبي فيلچااا':'unknown','الله ثم الوطن الكويت ثم الأمير':'Kuwait',
                    'de la vrg':'unknown','القدس   فلسطين':'Palestine','جدة':'KSA','Elmansoura':'Egypt','Makkah':'KSA','Giza  Egypt':'Egypt','Immigrant since 2008':'unknown',
                    'Liverpool  England':'UK','egypt':'Egypt','دار الصباح':'unknown','الجزائر  ':'Algeria','TEHRAN':'IRAN','قانا الأبيّة':'unknown','Stockholm  Sweden':'Sweden',
                    'خلف الحزن بدمعه ':'unknown','جنوب لبنان':'Lebanon','سادة اشراف جئنا من الحجاز':'KSA','Druzistan':'unknown','المدينه المملكة العربيه السعوديه':'KSA','Dam  Egypt':'Egypt',
                    'قنا  مصر':'Egypt','يارب رضاك والجنه':'unknown','Middle East   الشرق الأوسط':'unknown','KUWAIT   ':'Kuwait','محافظة معان':'Jordan',
                    'جلب الحبيب فك السحر رد المطلقه':'unknown','zagazig':'unknown','الرياض  المملكةالعربيةالسعودية':'KSA','Dammam':'KSA','28 degrees above the equatter':'unknown',
                    'في جميع أنحاء العالم في متعدد':'unknown','بورسعيد  مصر':'Egypt','جريدة إلكترونية':'unknown','الجنوب':'Lebanon','Hai i m Malaysian':'Malaysia',
                    'كوكب عطارد':'unknown','Montr al  Qu bec et Beyrouth':'Lebanon','iraq':'Iraq','Mount Lebanon':'Lebanon','الضاحية الجنوبية':'Lebanon',
                    'باريس، فرنسا  ':'France','Qena  Egypt':'Egypt','       ':'unknown','ليبيا':'Libya','القدس المحتلة':'Palestine','نجران  المملكة العربية السعودي':'KSA',
                    'لبنان المقاوم':'Lebanon','snap drmohamadalhdl':'unknown','Shinas  Oman ':'Oman','Jeddah  Kingdom of Saudi Arabi':'KSA','Rak':'unknown',
                    'GREAT UAE':'UAE','شي فنجان قهوة  ':'unknown','South Lebanon':'Lebanon','north   lebanon':'Lebanon','هنا و الآن':'unknown','فهدالهديب':'unknown',
                    'Dr Soliman Fakeeh Hospital':'KSA','الريان  دولة قطر':'Qatar','الوطن العربي':'unknown','tripoly':'Lebanon','DXB UAE SUDAN':'UAE',
                    'قهوة الفرزلي':'unknown','العلا':'KSA','Islamic Republic of Iran':'IRAN','Mansora  faculty of engineerin':'KSA','Jordan   MidEast':'Jordan',
                    '   ':'unknown','Amman  Jordan':'Jordan','إنسان كوني':'unknown','فوق السحاب وميت ظماء':'unknown','paradise':'unknown',
                    'Al Khaldiya  Kuwait':'Kuwait',' ساقلته سوهاج  مصر':'Egypt','Sharjah  United Arab Emirates':'UAE','Qadsia Kuwait':'Kuwait','Chicago  IL':'USA',
                    'T rkiye':'Turkey','Riyadh  Kingdom of Saudi Arabi':'KSA','maroc':'Morocco','Al Khobar':'KSA','بلاد الله':'unknown','الضاحية الجنوبية':'Lebanon',
                    ' جده':'KSA','Dekwaneh':'Lebanon','Tanta  Egypt':'Egypt','Kafr El Shikh  Egypt':'Egypt','Retweets endorsments':'unknown',
                    'Cairo  Egypt ':'Egypt','London':'UK','Uttar Pradesh  India':'India','الطائف ؛ محافظة ميسان':'KSA','Adma  Lebanon':'Lebanon','الجَنوبُ المُقَدَّسْ':'Lebanon',
                    'Tala  Menofia':'Egypt','Palestine،gaza':'Palestine','الجيزة':'KSA','سويسرا الشرق':'Lebanon','مركز الفارابي للروحانيات':'unknown','Istanbul':'Turkey',
                    'الحساب مشترك  ':'unknown','kSA':'KSA','منتصف الطريق':'unknown','  جبل عامل  ':'unknown','Egypt المحروسة   ':'Egypt','Chuo  Nakano  Tokyo':'Japan',
                    'The Kingdom of Saudi Arabia':'KSA','ابها  المملكة العربية السعودية':'KSA','الواقع':'unknown','Bahrain  GCC':'Bahrain','هون و هونيك':'unknown',
                    'سلطنة عمان مسقط':'Oman','T rkiye ':'Turkey','Lebanon  Byblos':'Lebanon','هاربة من المجتمع المستشرف ':'unknown','Saudi arabia':'KSA',
                    'الشارقة  دولة الإمارات العربية':'UAE','انا الجمبرياية':'unknown',' بيروت لبنان ':'Lebanon','الأحساء':'KSA','  بقلبـه المطي ':'unknown','najran kingdom of saudi arabia':'KSA',
                    'Egypt Lake Leto  FL':'Egypt','السعودية   الرياض':'KSA','Lebanon  El Mta n ':'Lebanon','Gutech ':'Germany',
                    'Gen ve  Suisse  الجزائر  ':'Algeria','kuwait city   kuwait ':'Kuwait','El Fayoum Egypt':'Egypt','Dubai   UAE':'UAE','Ksa  bah ':'KSA','Aswan  Egypt':'Egypt',
                    'جمهورية السيد حسن نصرالله':'Lebanon','بين النجوم':'unknown','غابة':'unknown','Jeddah  Kingdom of Saudi Arabia':'KSA','North Lebanon':'Lebanon',
                    'الحفير':'KSA','Amman  Hashemite Kingdom of Jordan':'Jordan','Tokyo to  Japan':'Japan','بين عدالة السماء وقانون الأرض':'unknown','carrd byf':'unknown',
                    'Naccache  Lebanon':'Lebanon','حيث لا حياة':'unknown','Alexandria Egypt':'Egypt','المدينة مملكة العربية':'KSA','Baghdad':'Iraq','جنوب':'Lebanon',
                    'اسطنبول تركيا ':'Turkey','JORDAN':'Jordan','F K K ':'unknown','دولة الإمارات العربية المتحدة':'UAE','Beni Suef  Egypt':'Egypt','area 51':'unknown',
                    'طبرجل  المملكة العربية السعودي':'KSA','الأحساء   السعودية':'KSA','NahrIbrahim':'Lebanon','تحت اقدام أمي  خارج السرب  ':'unknown','Deir El ahmar':'unknown',
                    'Dubai':'UAE','ام الطنافس':'unknown','  غزة فلسطين':'Palestine','Beirut  Lebanon ':'Lebanon','amman jordan':'Jordan',' حيث توجد الكرامة':'unknown',
                    'عند كل مستضعف':'unknown',' alotaibi':'unknown','Mansoura':'KSA','Phoenician State ':'Lebanon','Alg rie':'unknown','majlis news com':'unknown',
                    'الله الوطن الامير':'unknown','Provence Alpes C te d Azur  France':'France','بص ع اللوكيشن':'unknown','Las Americas':'USA','فلسطيني بالاختيار ':'Palestine',
                    'Berlin  Deutschland':'Germany','عروس تهامة':'KSA','Riyadh  ':'KSA','تنقل مستمر':'unknown','HIJAZ':'KSA','ب عالي الشواهيق  ':'unknown',
                    'Kafr El Shikh  Egypt Dubai UAE':'UAE','قنا  مصر':'Egypt','Irvine  CA':'USA','نجد العذيه Naga hamady':'unknown','المدينة النبوية المنورة':'KSA',
                    'Gen ve  Suisse':'unknown','Global Worldwide':'unknown','بالبيت ببعلبِك':'Lebanon','gaza':'Palestine','بوصل طلبيات و بحب شغلي كتير':'unknown',
                    '12 Street Attar   Osim   Giza':'Egypt',' القدس ':'Palestine','ksaالشرقية  ':'KSA','Lebanon Beirut':'Lebanon','Baltim':'KSA','K S A':'KSA',
                    'حضرموت  ':'Yemen','Akkar':'Lebanon','229':'unknown','Dammam  Kingdom of Saudi Arabi':'KSA','Amman  Jordan 11118':'Jordan',
                    'رأس غارب  مصر':'Egypt','God bless you':'unknown','الطائف':'KSA','التلاويه دوله وانا فرد منها':'unknown','West Asia ':'unknown','tripoli lebnen':'Lebanon',
                    'The Jordanian Badia ':'Jordan','Syria  ':'Syria','Lebanon   Australia':'Lebanon','تبوك':'KSA','Farmville':'unknown','منطقة الجوف  محافظة القريات':'KSA',
                    'KW for now':'Kuwait','Nabatieh  South Lebanon':'Lebanon','جوة الدنيا':'unknown','Montreal Canada':'Canada','Syrian Arab Republic':'Syria',
                    'لبنان  شبعا':'Lebanon', '  بقلب امي':'unknown','Leicester  England':'UK','العراق  النجف الاشرف':'Iraq','صور  سلطنة عمان':'Oman','بني سويف':'KSA',
                    'حيث يجب أن نكون سَنَكون':'unknown','Jeddah  Saudi Arabia':'KSA', 'رفحاء  المملكة العربية السعودي':'KSA','فلسطين  خانيونس ':'Palestine','بيروت  لبنان ':'Lebanon',
                    'جازان  المملكة العربية السعودي':'KSA','الرياض  المملكة العربية ':'KSA','دولة الكويت  ':'Kuwait','المملكةالعربيةالسعودية  الجنوب':'KSA',' دولة الكويت العظمى ':'Kuwait',
                    'في قلب من أحبهم أكون  ':'unknown','كفر منصور الدوله  ':'unknown','على سواحل بلادي العذيّه ':'unknown','المصنعه':'KSA','الكويت   حرسها الله  ':'Kuwait', 'الطائف ':'KSA',
                    'الامارات العربية المتحدة':'UAE','حائل قطعة من قلبي  ':'KSA',' أرض ربي تنومة شعف آل سودة ':'unknown','ناشط لاشط':'unknown','الولايات المتحده الصدامية  ':'unknown',
                    'الكويت في المناهج العراقية ':'Kuwait','السعودية العظمى':'KSA','السعودية  ':'KSA','قطر العز والخير   تميم المجد  ':'Qatar','Egypt مصر':'Egypt','حسابي الاساسي':'unknown',
                    'عجمان، الإمارات':'UAE','ابوظبي جنة الأمن والأمان ':'UAE','فيلچا ياحبيبي فيلچااا  ':'unknown','الجزائر':'Algeria','دار الصباح  ':'unknown','باريس، فرنسا':'France',
                    'الضاحية الجنوبية  ':'Lebanon', 'جده ':'KSA','جبل عامل  ':'KSA','منتصف الطريق  ':'unknown','بقلبـه المطي  ':'unknown','انا الجمبرياية ':'unknown', 
                    'اسطنبول تركيا':'Turkey','جنوب ':'Lebanon','غزة فلسطين  ':'Palestine',' عند كل مستضعف':'unknown','حيث توجد الكرامة':'unknown','نجد العذيه':'unknown',
                    'قنا  مصر Naga hamady':'Egypt','بقلب امي  ':'unknown'}

def replace_arabic(text):
    new = text.replace(arabic_location_mapping)
    return new


# In[2]:


#create a mask to replace specific locations with their countries
english_location_mapping = {'Escrow':'unknown','Aberdeen  UK':'UK','M TROPOLE DE LYON':'France','God s Country Toronto Canada':'Canada',
          'Atlanta GA':'USA','Lenape Land Brooklyn':'USA','Boston  MA ':'USA','Nice Paris':'France','Washington  DC':'USA',
          'Everywhere you want to be':'unknown','Washington State':'USA','Ki  Earth ':'unknown','1986':'unknown',
          'Free':'unknown','Missouri  USA':'USA','Plague Island':'UK','Texas  USA':'USA','Brooklyn  NY':'USA',
          'Brisbane  Australia':'Australia','Vadodara India':'India','Maryland    ':'USA','Los Angeles  California':'USA',
          'Salt Lake City  Utah  USA':'USA','Malacca Malaysia':'Malaysia','North Nottinghamshire':'UK','Mumbai  India':'India',
          'Lagos  Nigeria':'Nigeria',' She Her South east Asian':'unknown','EU the biggest market on Earth':'unknown',
          'Houston  TX':'USA','Blocks racists and bores ':'unknown','Hyderabad  India':'India','Liverpool':'UK',
          'Nairobi  Kenya':'Kenya','Newbury  Berkshire':'UK','UK  ':'UK','The Puzzle Palace':'unknown',
          'Cobh  Co  Cork  Ireland':'Ireland','everywhere':'unknown','South Carolina  USA':'USA','San Diego  CA':'USA',
          'Portsmouth':'UK','Manchester':'UK','Bethesda  MD':'USA','Coastal Oz':'unknown','Texas':'USA','Abuja  Nigeria':'Nigeria',
          'Liban':'Lebanon','multifandom  BLM':'unknown','England':'UK','America First':'USA','Las Vegas  NV':'USA',' ':'unknown',
          'Memphis  TN':'USA','SoCal':'unknown','chicago':'USA','Coastal   Western Australia':'Australia','London':'UK',
          'South West  England':'UK','Catalonia':'Spain',' DM V  to Soufend SEA':'unknown','Newark California':'USA',
          'Silver Millenium':'unknown','The Good Old North State':'USA','London  England':'UK','Vancouver  BC':'Canada',
          'Princess Park':'UK','Tokyo  Japan':'Japan','Iowa  USA':'USA','NW Arkansas':'USA','Dunwoody  GA':'USA','New York  NY':'USA',
          'Bristol':'UK','Toronto  Ontario':'Canada','Nottingham':'UK','New Jersey  USA':'USA','Georgia  USA':'USA',
          'procrastination station':'USA','Cheadle  England':'UK','Newcastle Upon Tyne  England':'UK','South Somerset   London area':'UK',
          'Eleio Pronoi  Greece':'Greece','Toronto  Ontario  Canada':'Canada','TEXAS':'USA','United States':'USA','Toronto ON Canada':'Canada',
          'YYZ':'unknown','Saint Lucia':'UK','Pretoria  South Africa':'South Africa','Somewhere up North ':'unknown','Queens  NY':'USA',
          'Toronto':'Canada','Florida  USA':'USA','U K':'UK','morpeth   Girona':'France','Philadelphia  PA':'USA','Ontario':'Canada',
          'Wales':'UK','Boise  ID':'USA','W A T P  uk':'UK','Wurundjeri land':'Australia','Scotland  United Kingdom':'UK',
          'Saskatoon  SK':'Canada','Columbus   OH':'USA','East Haven  CT':'USA','Anwick Lincolnshire UK':'UK','Bs  As':'unknown',
          'Manchester  England':'UK','california':'USA','Florida':'USA','Yorkshire':'UK','Hackney  London':'UK','California   USA':'USA',
          'Santa Rosa  CA':'USA','England  United Kingdom':'UK','Dublin City  Ireland':'Ireland','Nassau County  NY':'USA','Louisiana  USA':'USA',
          'West Molesey Surrey  Now Essex':'unknown','Ogun State  Nigeria':'Nigeria','Lagos':'Nigeria','Austin  via the 8th Dimension':'unknown',
          'IRL  NL  USA':'USA','Devon  UK':'UK','Harare  Zimbabwe':'Zimbabwe','yorkshire  uk ':'UK','United Kingdom':'UK',
          'Edmonton  Alberta':'Canada','Clemson  SC':'USA','Salisbury Wiltshire':'UK','Indiana  USA':'USA','Somewhere in Canada ':'Canada',
          'Tijuana San Diego Ensenada':'USA','Northern California':'USA','Kildare  Ireland':'Ireland','Always somewhere new':'unknown',
          'Big Sky Country':'USA','Leicester  England':'UK','uk':'UK','California  USA':'USA','Cape Town  South Africa':'South Africa',
          'Hamburg  Deutschland':'Germany','Barnsley  England':'UK','Upstate NY':'USA','Doncaster  England':'UK','Cairo  Egypt':'Egypt',
          'Los Angeles':'USA','Bhubaneshwar  India':'India','London shithole':'UK','North Carolina  USA':'USA','Kingston  Ontario':'Canada',
          'Monroe  La ':'USA','New York  USA':'USA','Right in front of my laptop ':'unknown','On the toilet':'unknown','Chicago  IL USA':'USA',
          'Global Worldwide':'unknown','Columbus  OH':'USA','Sao Paulo  Brazil':'Brazil','HQ   Cambridge  England':'UK','irkalla':'unknown',
          'Ontario  Canada':'Canada','Atlanta to Seattle':'USA','North America':'unknown','Providence  Rhode Island':'USA',
          'Ohio  USA':'USA','Cape Town':'South Africa','Edinbrugh':'Scotland','Wherever my chem is':'unknown','Lower Somercotes Derbyshire ':'UK',
          'Phoenix  AZ':'USA','London   Paris':'UK','Leicester':'UK','Quiet Desperation Ln':'unknown','Nigeria  ':'Nigeria',
          'ISLA BERMEJA':'unknown','M xico':'Mexico','Covington  LA':'USA','hyyh':'unknown','Rural Goodhue County  MN  USA':'USA',
          'San Antonio  TX':'USA','Providence  RI':'USA','Cottingley  England':'UK','DFW':'USA','Bali  Indonesia':'Indonesia','New Delhi  India':'India',
          'Birmingham  England':'UK','S E  United States':'USA','Iron Range  Minnesota':'USA','Chicagoland':'USA','Riverside  CA':'USA',
          'Someplace':'unknown','The World':'unknown','Seattle  for now ':'USA','Mount Albert Canada':'Canada','UK  Devon':'UK','Londin':'UK',
          'YO16 6TW':'unknown','Glasgow':'Scotland','Cowdenbeath':'Scotlan','NJ':'USA','Tucson  AZ':'USA','beautiful north wales':'UK',
          'Self imposed exile ':'unknown','Bloomfield Hills  MI':'USA','Oregon  USA':'USA','New York City':'USA','Melton Mowbray  England UK':'UK',
          'Marlborough':'UK','Jacksonville  FL':'USA','nottingham':'UK','Ukiah  CA':'USA','Palma de Mallorca':'France','West Midlands':'UK',
          'Dubai  United Arab Emirates':'UAE','between heaven and earth  but ':'unknown','Here And Now':'unknown','Paradise  NV':'USA',
          'derbys':'UK','Los Angeles  CA':'USA','Regina  SK':'USA','Indiana':'USA','Park Heights  MD ':'USA','Westport':'UK','Hogworts':'unknown',
          'Virginia  USA':'USA','Norfolk UK':'UK','global':'unknown','knocking about':'unknown','Kwa Mashu  South Africa':'South Africa',
          'Oakland  CA':'USA','Pittsburgh  PA':'USA','Adelaide  South Australia':'Australia','Fort Worth  TX':'USA','Syracuse  NY':'USA',
          'Greater  Manchester':'UK','EUROPE   OCEAN INDIEN AFRIQUE ':'unknown','No One Gives A Fuck Island':'unknown','Glasgow  Scotland':'Scotland',
          'alki beach seattle':'USA','Nungua rich city  MAAMI':'USA','he him 17':'unknown','Citizen at Large':'unknown','Washington  USA':'USA',
          'North West  England':'UK','NE Bumblefuck  USA':'USA','New Delhi':'India','Norwich  England  ':'UK','Chicago  IL':'USA','formally blackburn now ireland':'Ireland',
          'Wales  United Kingdom':'UK','USA CDA':'USA','West yorks':'UK','Bearna Gaillimh ':'Ireland','Present ':'unknown','Bloemfontein':'South Africa',
          'Toledo  OH':'USA','Comox  British Columbia':'UK',' J tul uk':'UK','New York City  USA':'USA','Kenyan Diaspora':'Kenya','Seattle  Cleveland transplant ':'USA',
          'Hell Hades Mictlan Tartarus':'unknown',' T  35 488497 97 526792':'unknown','Tallahassee  FL':'USA','Wherever the Pepper Sauce Is':'unknown',
          'from the internet':'unknown','j ':'unknown','East Coast Australia':'Australia','Lodz  Poland':'Poland','Harrisburg  PA':'USA','The Real World':'unknown',
          'Boston':'UK','Salford     Creuse  ':'unknown','Bristol UK':'UK','Palmerston Ontario Canada':'Canada','London and Richmond  VA':'USA',
          'London  UK':'UK','Detroit  MI':'USA','West Yorkshire  England':'UK','Syracuse NY':'USA','N A KHH AN KN B':'unknown','Mesa  AZ':'USA',
          'Space':'unknown','Stoke on Trent  England':'UK','Lebanon  TN':'Lebanon','Mount Desert Island  Maine':'France','Brampton Ont':'Canada',
          'Sydney  Australia':'Australia','Up A TreeHouse':'unknown','Oklahoma  USA':'USA','South African staircase':'South Africa',
          'media bubble':'unknown','France   Singapore':'France','far too online for my own good':'unknown','MA  USA':'USA','Rome  Lazio':'Italy', 
          'NYC':'USA',' 9ll NWO  Nuclear  FalseFlag ':'unknown','far away in a cold dark place':'unknown','EU  ':'unknown','worldwide':'unknown', 
          'Karlsruhe  Germany':'Germany','Jackson Heights  Queens':'USA','In a cage ':'unknown','JHB   CPT           MAGA  MAGAPOWERED  Trump2020':'USA',
          'Europe':'unknown','Say  that s a swell map ':'unknown','Sydney  New South Wales':'Australia','FL  ':'USA','European Union':'unknown',
          'she they 18  ':'unknown', 'Wichita  Kansas':'USA','Canada Water':'Canada','New York  ':'USA','Sagres':'Portugal','   FL resister':'USA',
          'Covina  CA':'USA','Kochi  India':'India','Brussels':'Belgium','Leicestershire  England ':'UK','Coralville  IA':'USA','ATX':'unknown',
          'Boozer':'unknown','The South  ':'unknown','Maryland  USA':'USA','Beautiful California  ':'USA','Hedge End  England':'UK','Williamsburg':'USA','Cottenham  Near Cambridge ':'UK',
          'Wet Market  Wuhan  China ':'China','Your Network':'unknown','Richmond  Virginia':'UK','Johannesburg  South Africa':'South Africa',
          'Twickenham  UK':'UK','Tulsa  OK':'USA','Wisconsin':'USA','Duchy Vultjag':'unknown','Austin  TX':'USA','Kano  Nigeria':'Nigeria',
          'Cumbria ':'UK','Wall St  New York  NY':'USA','Columbus OH':'USA','Southern California  ':'USA','Incoming      ':'unknown','Bury':'unknown',
          'Rhode Island':'USA','Everywhere':'unknown','I just work here':'unknown','KOCHI':'India','Fayetteville  AR':'USA','Islington':'UK',
          'The Pentagon':'USA','Morecambe Bay   England':'UK','Northern NSW':'USA','Harare':'Zimbabwe','Illinois':'USA','St  Louis':'USA','Wenatchee  WA':'USA',
          'Caterham  Surrey  UK':'UK','Iowa':'USA','nr Treviso':'Italy','   TheRealDonEast Hiram  GA':'USA','Hawaii Kohala Coast Big Island':'USA',
          'Bradford  UK':'UK','The Shire':'New Zealand','Bageshwar  India':'India','Raleigh  NC':'USA','Nig ga':'unknown','North America ':'unknown',
          'Massachusetts  U S A ':'USA','Mostly Chicago  IL ':'USA','Toronto  ON':'Canada','Washington  D C ':'USA','Earth  Africa':'unknown','Michigan  USA':'USA',
          'Rated Top 1  Twitter Influencer by  Klear  the leading Influencer Marketing Platform ':'unknown','Cleveland  OH':'USA','Pittsburgh PA':'USA',
          'Cheshire':'UK','vegas  where else':'USA','Uk':'UK','Farmville':'USA','Oadby  England':'UK','near bath':'unknown','London  United Kingdom':'UK',
          'london':'UK','Caerleon  Wales':'USA','Oxfordshire':'UK','Connecticut  USA':'USA','Dirty jerz':'USA','Henderson  NV':'USA',
          'Ann Arbor  MI':'USA','Ankara merkezli':'Turkey','she her':'unknown','Kailash   ':'China','British Columbia  Canada':'Canada',
          'Meath  Ireland':'Ireland','Sungai Petani Kedah':'Malaysia', '   ':'unknown','Southeast of Disorder  CA':'USA','Northern Alabama':'USA',
          'Vancouver  Canada':'Canada','Miami  FL':'USA','dapits com':'unknown','England  UK':'UK','Lala Land':'unknown','Athens':'Greece','Seattle  WA':'USA',
          'Koraput  India':'India',' ZA':'unknown','Natstown':'USA','Singapore  ':'Singapore','Calgary  Alberta':'Canada','Distrito Federal  M xico':'Mexico',
          'Midwest':'USA','Shelf  England':'UK','15   he they':'unknown','Crinkley Bottom':'UK','Las Vegas Florida  USA':'USA','Barbados  ':'USA',
          'Coventry  England ':'UK','Yorkshire and The Humber':'UK','Ealing  London':'UK','Milwaukee  WI':'USA','San Antonio  TX    District 20':'UK',
          'Hightstown  NJ':'USA','Brisbane  Queensland':'Australia','Barnard Castle Eyetest Centre':'UK','Chicagoland  USA':'USA','Jordaan  Amsterdam':'The Netherlands',
          'North Carolina':'USA','Cornwall  and France ':'France','ON  CA    http achama biz ly':'USA','Manchester Swansea':'UK','Bedfordshire  UK':'UK',
          'San Bernardino  CA':'USA','Bakersfield  CA':'USA','Tunbridge wells':'UK','Compton  CA':'USA','Plano  TX':'USA','Bedworth UK':'UK',
          'Usually Essex  UK ':'UK','Mars USA 127 0 0 1':'USA','Bonny  in  Rivers  state':'USA','Wisconsin  USA':'USA','Minnesota  USA':'USA',
          'lebanonatheart':'Lebanon','Helsinki  Tellus':'unknown','in my head':'unknown','Stolen land  TX ':'USA','Melbourne  Victoria':'Australia',
          'Land   Wahpekute   Ochethi Sak':'unknown','Southampton  UK':'UK','Wittenberg University':'USA','Meerdaal':'Belgium','Long Island  NY':'USA',
          'Norman OK':'USA','Maip  Chile':'Chile','Random   Omnipinut':'unknown','Chandigarh  India':'India','Alberta  Canada':'Canada',
          'Denver  CO':'USA','Watertown  NY':'USA','Milton Keynes Council':'UK','Little Rock  Ark ':'USA','Rotterdam  The Netherlands':'The Netherlands',
          'Guernsey  Channel Islands':'UK','Columbus  Ohio':'USA','Nova Scotia':'Canada','Skyrim':'unknown','Alabama':'USA',
          'Galway  Ireland':'Ireland','Berkeley  Ca':'USA','Brooklyn  NY   Yazoo  MS':'USA','Des Moines  IA':'USA','Gravett Island':'unknown',
          'South Carolina':'USA','Fort Smith  arkansas':'USA','Puerto Rico  USA':'USA','Akure':'Nigeria','Milton Keynes':'UK','Leipzig  Germany':'Germany',
          'RTs and Likes   Endorsement':'unknown','In Your FeEliNgS ':'unknown','noreg':'Norway','S 26  10  0    E 27  42  0 ':'unknown','Hollywood  CA':'USA',
          'Thane Poor cousin of Mumbai':'India','Salamandastron':'unknown','Tigard  OR':'USA','La Celle Saint Cloud  Ile de France':'France',
          'Texas State University    TXST CLS':'USA','Bangalore':'India','Dublin':'Ireland','Lewisville  NC':'USA','Everywhere ':'unknown',
          'In the south':'unknown','Fucked UK':'UK','London  England  ':'UK','Dagobah':'unknown','Adelaide  Australia':'Australia','Bend  OR':'USA',
          'Dartmouth  MA USA':'USA','North Wales UK':'UK','Hilton  NY':'USA','Fly Over State':'unknown','SF Bay Area':'USA','Hazard Kentucky':'USA',
          'Melbourne Australia':'Australia','Scunthorpe':'UK','Oregon':'USA','Cumbernauld  Scotland':'Scotland','the worst country ever':'unknown',
          'Lagos  TX':'USA','Johnson City':'USA','West of Everything':'unknown','UK Police state':'UK','South Yorkshire':'UK','Rhein Main Cocooning':'unknown',
          'Hanging In The Air':'unknown','Kilkenny  Ireland':'Ireland','Village Thatched Roof Cottage':'UK','Maryland':'USA','Ashton under Lyne  England':'UK',
          'Midlands and Suffolk':'UK','Malaysia ':'Malaysia','University of the Philippines':'Philippines','Maidstone':'UK','London  Tech City':'UK',
          'Outwood   Samui':'unknown','With the people ':'unknown','Dunnville':'USA','Cape Republic':'South Africa','Austin  Texas  USA':'USA',
          'The NSA Knows':'unknown','Namibia':'South Africa','Ottawa  Ontario':'Canada','We live in a society ':'unknown','Fort Lauderdale  FL':'USA',
          'yes':'unknown','Tl n':'unknown','San Francisco  CA':'USA','Jools  UK':'UK','Norwich':'UK','UL Hospitals Group':'unknown',
          'Madrid':'Spain','West Suffolk':'UK','Paignton':'UK','Passaic  NJ':'USA','Wolverhampton  England':'UK','San Francisco':'USA',
          'Long Island':'USA','searching ':'unknown','ROCHESTER  NY':'USA','Bury  England':'UK','Bogot  D C  Colombia':'USA','In my house':'unknown',
          'Pittsburgh':'USA','In between some thick thighs':'unknown','Northern Ireland  United Kingdom':'UK','Manchester England':'UK',
          'Beirut  Lebanon':'Lebanon','Great Britain':'UK','Northallerton':'UK','Oldham  England':'UK','Tribal inland territories':'unknown',
          'Baltimore  MD':'USA','San Marcos  TX':'USA','Lawrenceville  GA':'USA','CA':'USA','https ifers 123 st ':'unknown','Wrong Side of Cottage Country':'unknown',
          'Pierrefonds QC':'Canada','South':'unknown','World':'unknown','Southampton UK':'UK','Western Washington':'USA','La Plata County  Colorado':'USA',
          'Tannh user Gate':'unknown','Baambrugge  De Ronde Venen':'The Netherlands','Vaguely here':'unknown','Nr Cadwell Park  UK':'UK','Osoyoos  British Columbia':'UK',
          'Milkyway':'unknown','myHOMEmyCastle  NOTmyPRISON':'unknown','The Gulf Of Mexico ':'Mexico','Naperville  IL':'USA','North Texas':'USA',
          'Wasaga Beach  Ontario':'Canada','Brittany  North Wales soon':'unknown','Kingsport TN':'USA','DMV':'unknown','Heysham     Dales     Lakes':'USA',
          'fbi basement office':'USA','Waukesha  Wisconsin':'USA','Lahaina  HI':'USA','should be in egypt ':'unknown','Huddersfield  UK':'UK','DC NC':'USA',
          'Olney  MD':'USA','Sunderland':'unknown','North West England  UK':'UK','University of Oregon  SF Marin':'USA','Hong Kong':'China',
          'zombieland':'unknown','kingston  Jamaica':'Jamaica','Leicester  Leics   Rutland':'UK','Devon':'UK','Stratford Upon Avon':'unknown',
          'Sydney  Melbourne  Adelaide':'Australia','GOD BLESS AMERICA ':'USA','Hy Brasil':'Brazil','Kerry  Ireland':'Ireland','brooklyn':'USA',
          'Concord  NH':'USA','Guildford  England':'UK','San Jose  CA':'USA','Sittingbourne  Kent':'USA','Cincinnati  OH':'USA','Edinburgh  Scotland':'Scotland',
          ' hinehou   Te Whakaraup ':'unknown','Wokingham  England':'UK','North London':'UK','Bridgend   Wales':'UK','Timbuktu':'Mali',
          'Copenhagen':'Denmark','gravesend  kent  england':'UK','New York':'USA','Dunny on the Wold':'unknown','Finger Lakes Region   NYS':'USA',
          'Kampala  Uganda':'Uganda','he him':'unknown','Hollywood':'USA','Bihar  India':'India','North Herts  Cambridge':'UK','Kilimanjaro  Tanzania':'Tanzania',
          'Canton Mi':'USA','Igloo':'unknown','Chennai  India':'India','Cambridge  England':'UK','West Bromwich  England':'UK','United States of America':'USA',
          'Palatine  IL':'USA','Pennsylvania  USA':'USA','Iowa via CA via MO via OK':'USA','Davie  FL':'USA','Global':'unknown','Boston  MA':'USA',
          'Massachusetts  USA':'USA','Newburyport':'USA','Global nomad mostly Europe atm':'unknown','Twin Cities':'unknown','Land of the Prince Bishops':'UK',
          'Bull Mountain  OR':'USA','new orleans':'USA','stanbul  T rkiye':'Turkey','South West Surrey':'USA',' T  40 743972 74 010354':'unknown','Independence  MO':'USA',
          'Northants Oxon Bucks borders':'UK','Seattle':'USA','Behind the fence in California':'USA','Rajapur prayagraj':'India','Manchester UK':'UK',
          'Canberra  Australian Capital Territory':'Australia','Andheri West  Mumbai':'India','San Jose  California':'USA','Camden Town  London':'UK',
          'Arlington  VA':'USA','Dublin nurtured  now Galway':'Ireland','Nowhere yet everywhere':'unknown','Dublin  Ireland':'Ireland','Near the Wadden Sea ':'unknown',
          'New Zealand   Maldives  ':'New Zealand','Hell on Earth':'unknown',' teamKent':'USA','Ulverston':'UK','Geneva':'Switzerland','Polokwane  South Africa':'South Africa',
          'BC  Canada':'Canada','LONESOME TOWN   TEXAS':'USA','In my head ':'unknown','Ireland ire  ':'Ireland','  NO guilt   unapologetic':'unknown','Treaty 7  Alberta':'Canada',
          'Amiskwac w skahikan':'unknown','diciamo in Toscana ':'unknown','West Sussex':'UK','EARTH':'unknown','Dubai  UAE':'UAE','Roanoke  VA':'USA',
          '0 0  0 0  Plural Zed  Alpha':'unknown',' T  38 946904 77 333847':'unknown','Laguna Beach  CA':'USA','Catalunya':'Spain','Melissa  TX':'USA',
          'Perry Barr CLP  Birmingham  UK':'UK','Valencia  California':'USA','HMP England  House Arrest':'UK','SOUTH Wales  United Kingdom':'UK',
          'TwitterVille':'unknown', 'hull':'UK',' stanbul  T rkiye':'Turkey'}

def replace_english(text):
    new = text.replace(english_location_mapping)
    return new


def features_list(text, num):
    features_list = []
    for index, name in enumerate(text.value_counts().index.tolist()):
        values = text.value_counts()[index]
        if values < num:
            features_list.append(name)
    return features_list

